---
- hosts: "{{ host }}"
  tasks:
    # criar a pasta para guardar o docker-compose-yml
    - name: "Create {{ application }} folder"
      file:
        path: /home/{{ user }}/{{ application }}
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
      become: yes
      become_user: "{{ user }}"
    
    # copiar o arquivo de docker-compose
    - name: "Create docker-compose.yml"
      template:
        src: docker-compose.yml
        dest: /home/{{ user }}/{{ application }}
        mode: 0666
        owner: "{{ user }}"
        group: "{{ user }}"
    
    # parar o docker-compose da aplicacao
    - name: "Docker {{ application }} compose stop"
      docker_service:
        project_name: "{{ application }}"
        project_src: "/home/{{ user }}/{{ application }}"
        state: absent
      become: yes
      become_user: "{{ user }}"

    - name: "Waiting docker-compose down"
      pause:
        seconds: 15

    # remove a imagem do {{ application }}
    - name: "Docker {{ application }} rmi"
      docker_image:
        name: nexus.devops.ifrn.edu.br/corporativo/{{ application }}:latest
        state: absent
      become: yes
      become_user: "{{ user }}"
    
    # atualizar a imagem do {{ application }}
    - name: "Docker {{ application }} pull latest"
      docker_image:
        name: nexus.devops.ifrn.edu.br/corporativo/{{ application }}:latest
      become: yes
      become_user: "{{ user }}"
    
    # executar o docker-compose {{ application }}
    - name: "Docker {{ application }} compose run"
      docker_service:   
        project_name: "{{ application }}"
        project_src: "/home/{{ user }}/{{ application }}"
      become: yes
      become_user: "{{ user }}"